Removed trailing whitespace, unneccesary line breaks, changed indentation style

diff --git a/release b/release
--- a/release
+++ b/release
@@ -19,25 +19,25 @@ VERSION=$1
 DATE=$(date +"%Y/%m/%d")
 
 if ! echo $VERSION | egrep -q "^[0-9]+\.[0-9]+\.[0-9]+$" ; then
-  echo "Error: version should be of the form 1.2.5 (major.minor.revision)."
-  exit 1
+	echo "Error: version should be of the form 1.2.5 (major.minor.revision)."
+	exit 1
 fi
 
 # TODO: instead of all this checking, just sed values into the appropriate files
 
 DATE_VERSION="$DATE v$VERSION"
 for file in $CLS_FILES $DEF_FILES ; do
-  if ! grep -q "$DATE_VERSION" $file ; then
-    echo "Error: $file does not contain '$DATE_VERSION':"
-    egrep 'Provides(Class|File)' $file
-    exit 1
-  fi
+	if ! grep -q "$DATE_VERSION" $file ; then
+		echo "Error: $file does not contain '$DATE_VERSION':"
+		egrep 'Provides(Class|File)' $file
+		exit 1
+	fi
 done
 
 VERSION_DATE="$VERSION - $DATE"
 if ! grep -q "$VERSION_DATE" History.txt ; then
-  echo "Error: no release notes for '$VERSION_DATE' found in History.txt"
-  exit 1
+	echo "Error: no release notes for '$VERSION_DATE' found in History.txt"
+	exit 1
 fi
 
 # Refresh sample documents
